# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0-beta8'
pod 'WYPopoverController', '~> 0.3.9'
pod 'DACircularProgress', '~> 2.3.1'
pod 'Masonry', '~> 0.6.4'
pod 'FMDB', '~> 2.6'
